export const operations = {
    TODAY: 'Today',
    TOM: 'Tomorrow',
    DAY_A_T: 'Day After Tomorrow',
    ADD_DAYS: 'Add Days',
    YESTERDAY: 'Yesterday',
    DAY_BEF_Y: 'Day Before Yesterday',
    NEXT_DAY: 'Next Day',
    NEXT_WEEK: 'Next Week',
    NEXT_MONTH: 'Next Month',
    NEXT_YEAR: 'Next Year',
    ADD_WEEK: 'Add Weeks',
    ADD_MONTH: 'Add Months',
    ADD_YEAR: 'Add Years',
    SUBTRACT_WEEK: 'Subtract Weeks',
    SUBTRACT_MONTH: 'Subtract Months',
    SUBTRACT_YEAR: 'Subtract Years',
    SUBTRACT_DAY:'Subtract Days',
    LAST_WEEK: 'Last Week',
    LAST_MONTH: 'Last Month',
    LAST_YEAR: 'Last Year',
}